# Generated by Django 2.1.5 on 2019-01-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190130_1506'),
        ('groups', '0003_auto_20181221_1758'),
    ]

    operations = [
    ]
